# Generated by Django 2.1.5 on 2019-02-05 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(max_length=10, verbose_name='玩家1')),
                ('person2', models.CharField(max_length=10, verbose_name='玩家2')),
                ('person3', models.CharField(max_length=10, verbose_name='玩家3')),
                ('person4', models.CharField(max_length=10, verbose_name='玩家4')),
                ('status', models.IntegerField(choices=[(0, '進行中'), (1, '已結束')], default=0, verbose_name='遊戲狀態')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('game_number', models.IntegerField(default=0, verbose_name='總局數')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(verbose_name='玩家1分數')),
                ('score2', models.IntegerField(verbose_name='玩家2分數')),
                ('score3', models.IntegerField(verbose_name='玩家3分數')),
                ('score4', models.IntegerField(verbose_name='玩家4分數')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記錄時間')),
            ],
        ),
    ]
