# Generated by Django 2.1.5 on 2019-02-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_round_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_number',
        ),
    ]
