# Generated by Django 2.1 on 2019-02-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_remove_game_game_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='person1',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='person2',
            new_name='player2',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='person3',
            new_name='player3',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='person4',
            new_name='player4',
        ),
    ]
